#!/usr/bin/env bash
#script that displays 'Best School' 10 times using until loopi
for ((i=1;i<=100;i++))
do
	if ! ((i%15))
	then
		echo Fizzbuzz
	elif ! ((i%3))
	then
		echo Fizz
	elif ! ((i%5))
	then
		echo Buzz
	else
		echo $i
	fi
done
