#!/usr/bin/env bash
#script that displays 'Best School' 10 times using until loopi
IFS=$'\n':
a=$(cut -d: -f1)
b=2
c=3
d=4
e=5
f=6
g=7
file=/etc/passwd
while read -r file
do
	echo "The user  is part of the $d gang, lives in $f and rides $g. $c's place is protected by the passcode $b, more info about the user here: $e"
done
