#!/usr/bin/env bash
#script that displays 'Best School' 10 times using until loop
if [ -e "school" ];
then 
echo "school file exists"
	if [ -s "school" ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ -f "school" ];
then
	echo "school is a regular file"
fi
else
	        echo "school file is does not exist"
fi
