#!/usr/bin/env bash
#script that displays 'Best School' 10 times using until loop
FILE=~/holbertonschool-shell/loops_conditions_and_parsing/school
if [ -e "$FILE" ];
then 
	echo "school file exists"
else 
	echo "school file does not exist"
fi
if [ -s "$FILE" ];
then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
if [ -f "$FILE" ];
then
	        echo "school file is a regular file"
fi
