#!/usr/bin/env bash
# init.d script
case "$1" in
	start)
		echo "pidof pidof" > /var/run/my_process.pid
		echo "manage_my_process started"
		./manage_my_process start &
		;;
	stop)
		if [ -f /var/run/my_process.pid ]
		then
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		pkill -f manage_my_process -15 &
		fi
		;;
	restart)
	       	echo "pidof pidof" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		pkill -f manage_my_process -15 &
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
