#!/usr/bin/env bash
#script that kills an infinite loop
case "$1" in
	start)
		sudo ./manage_my_process start &
		echo "pidof pidof" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		sudo pkill -f manage_my_process -15 &
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		sudo pkill -f manage_my_process -15 &
		echo "pidof pidof" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
